env_name: Hopper-v4

episodes: 1000
steps: 1000

# learning_rate: 0.0003
# learning_starts: 10000
# batch_size: 256
# train_freq: 1
# gradient_steps: 1

continue: True

learning_rate: 9.80828e-05
n_steps: 512
batch_size: 32
n_epochs: 5
gamma: 0.999
gae_lambda: 0.99
clip_range: 0.2
ent_coef: 0.00229519
vf_coef: 0.835671
max_grad_norm: 0.7

total_timesteps: 100000