env_name: MountainCarContinuous-v0

episodes: 1000
steps: 1000

algorithm: PPO
batch_size: 256
clip_range: 0.1
ent_coef: 0.00429
gae_lambda: 0.9
gamma: 0.9999
learning_rate: 7.77e-05
max_grad_norm: 5
n_epochs: 10
n_steps: 8
total_timesteps: 20000
vf_coef: 0.19