env_name: MountainCarContinuous-v0

episodes: 1000
steps: 1000

learning_rate: 7.77e-05
n_steps: 8
batch_size: 256
n_epochs: 10
gamma: 0.9999
gae_lambda: 0.9
clip_range: 0.1
ent_coef: 0.00429
vf_coef: 0.19
max_grad_norm: 5

total_timesteps: 20000