env_name: Pendulum-v1

episodes: 1000
steps: 1000

learning_rate: 0.001
n_steps: 1024
batch_size: 64
n_epochs: 10
gamma: 0.9
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5

total_timesteps: 100000